### ISSUE TITLE
schematic: consult with AMP-AD on data model structure

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#1087]
@avanlinden has been developing the AMP-AD data model schema to plug into the DCA testing instance for AMP-AD.

@avanlinden based on a conversation with @abbywall, it sounds like working with the schema does not produce the outputs that you'd intent. Let's sync up on the schema structure, and how to check it using schematic's REST API and schema visualization. 

@mialy-defelice could you reach out to @avanlinden for a consult?

**Comment by mialy-defelice** [comment]
@MiekoHash for visibility

- Spoke with @avanlinden and got access to the AMP-AD data model CSV and JSONLD.
- Tested the model locally within schematic and was able to successfully make the JSONLD without error and also make the manifests.
- Reached out to @afwillia to see if the problem was on the DCA side.
- He said the issue was the `config_schema.py` was not outputting any result from the function like expected.

**Expectation:**
```{
  "manifest_schemas": [
    {
      "display_name": "Biospecimen",
      "schema_name": "Biospecimen",
      "type": "record"
    },
    {
      "display_name": "Patient",
      "schema_name": "Patient",
      "type": "record"
    },
    {
      "display_name": "Bulk RNA-seq Assay",
      "schema_name": "BulkRNA-seqAssay",
      "type": "file"
    }
  ],
  "service_version": "v23.1.1",
  "schema_version": ""
}
```
**Result**
```
{
  "manifest_schemas": [],
  "service_version": [],
  "schema_version": []
}
```

- Using command line I was able to confirm that the data model should be able to return the correct results to the problem was probably related to the connection of the JSONLD to the DCA.
- The issue seems to have been with the `schematic_config.yml` file.
- They found the way the JSON LD was linked in the `schematic_config.yml` was incorrect. 
- Need to change the download_url to point to the raw GitHub JSONLD path, comment out the repo, and download the new workflow.
- Here is how the `schematic_config.yml` should look:

```
model:
  input:
    download_url: https://raw.githubusercontent.com/mc2-center/data-models/main/mc2.model.jsonld
    location: data-models/example.model.jsonld
    file_type: local
```

Closing issue since it has been resolved :)
