### ISSUE TITLE
Column headers are missing when using `manifest/generate` endpoint to return an existing manifest

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#1148]
**Describe the bug**
The issue was first reported by @afwillia 
Use the following parameters: 
* dataset_id = syn36003517
* asset_view = syn33715412
* output_format = excel

**Expected behavior**

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [x] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by afwillia** [comment]
![no-column-names-patient](https://user-images.githubusercontent.com/8195343/220459231-d13d822f-dcca-4b51-9e1b-c44b4a0a098a.png)

**Comment by afwillia** [comment]
also, the second sheet with the column specifications does not show up.

**Comment by milen-sage** [comment]
@afwillia and @linglp I updated this issue to critical, since we'd have to resolve before rolling out.

@afwillia is this a new behavior (i.e. this worked as expected before and only recently w/ updates from schematic it stopped working)? I remember discussing how the "Google"-free way of generating Excel spreadsheets was reproducing the functionality of "Google-based" sheets.

I'm not so concerned about the 2nd tab with the dictionary, but the headers, descriptions, formatting, dropdowns, etc.. all seem to be missing. This looks like a csv version of the data, except column names are missing as well.
