### ISSUE TITLE
Tests in develop branch are failing: errors rendered by Great Expectation 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#1169]
**Describe the bug**
For some reasons, tests in the `develop` branch are failing. Sample log can be found here: https://github.com/Sage-Bionetworks/schematic/actions/runs/4265741322/jobs/7425791711 and here: https://github.com/Sage-Bionetworks/schematic/actions/runs/4265843143/jobs/7425657642

@GiaJordan for awareness

**To Reproduce**

**Expected behavior**

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [X] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by linglp** [comment]
@mialy-defelice I filed an issue here

**Comment by GiaJordan** [comment]
Tests are failing because of the addition of [this manifest](https://www.synapse.org/#!Synapse:syn42173343) that is now interacting with the test manifest/mock data model validation rule for attribute `Check Match At Least`. Deleting this manifest should remedy this test failures, and I can issue a separate PR updating the validation rule, but there will likely be some kind of interactions with manifests given the nature of the rule.
@linglp @mialy-defelice
