### ISSUE TITLE
In JIRA: Endpoint that returns attributes of a given data model component

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/schematic#1174]
**Is your feature request related to a problem? Please describe.**
The Data Flow App needs a way to update configurations/dashboard columns/filtering options based on the attributes in the DataFlow Component. This will prevent schema changes from breaking the app and give users more flexibility with what they include in their groups DataFlow schema.

**Describe the solution you'd like**
Something similar to the `visualize/attributes` endpoint. Return a dataframe of attributes with information like description, required, valid values

**How important is this feature?** Select from the options below:
• 🌗 Medium 

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**
NA

**Comment by milen-sage** [comment]
@lakikowolfe there are a few functions in schematic: one each for [attribute description](https://sage-bionetworks.github.io/schematic/schematic/schemas/generator.html#SchemaGenerator.get_node_definition), [required](https://sage-bionetworks.github.io/schematic/schematic/schemas/generator.html#SchemaGenerator.is_node_required), and [valid values](https://sage-bionetworks.github.io/schematic/schematic/schemas/generator.html#SchemaGenerator.get_node_range); and one that [combines them](https://sage-bionetworks.github.io/schematic/schematic/schemas/explorer.html#SchemaExplorer). 

I can imagine the latter endpoint that combines all of that information would be the one you need? 

Generally, exposing these endpoints would be useful and straightforward; it is also aligned with a few user stories around creating and updating a data model. However, given bandwidth this sprint we may not get to that. If you could setup your code so that the only missing thing is the output from the endpoint (e.g. knowing the return formats of the function(s) above that should be possible) perhaps that  would allow you to make some progress?

We can then catch up with @linglp or @mialy-defelice towards the end of this sprint and check on prioritizing exposing the endpoint.

**Comment by lakikowolfe** [comment]
Sounds good. I'll look into these functions. Thanks @milen-sage!

**Comment by MiekoHash** [comment]
Moved to JIRA: https://sagebionetworks.jira.com/browse/FDS-102
