### ISSUE TITLE
Unable to generate link to Google Sheets templates

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#276]
I'm trying to set up the Data Curator App and schematic using the [instructions](https://docs.google.com/document/d/1MoTVogc5JouziQ9i7otf74qzBRIBHHNCJda6NAbRU_M/edit) that I wrote. I also recreated the file view to include both files and folders because it initially only included folders. However, my Shiny instance doesn't seem to be able to generate links to Google Sheets templates. Here's what it looks like: [screencast](https://drive.google.com/file/d/1CwUEzMKExY_laGyfLAX7PPy_1XsRDHv0/view). As you can see, the app doesn't crash, and there isn't an error in the [log file](https://drive.google.com/file/d/1TfXDVe7Nf6jLLkIHeumhwRLBlSr3osaI/view) other than the "Execution halted" from when I closed the webpage. Note that the Synapse setup (projects and file view) is based on what I was able to reverse-engineer, which may be completely wrong. 

I suspect this has to do with credentials, most likely for Google Drive/Sheets. Other than dropping with `credentials.json` file in the root of the schematic repo, what else is needed to ensure that the credentials work? 

**N.B.** Google Drive links will only work for Sage employees.

**Comment by allaway** [comment]
Looking at the current version of your instructions, I think you'll also need to do this (in the repo instructions but not yet in your google doc):

>Obtain the token.pickle file in schematic which is also necessary for authentication. If you do not already have this file run the metadata_usage example as follows inside schematic:
>`python examples/metadata_model.py`

**Comment by milen-sage** [comment]
@BrunoGrandePhD also, if @allaway 's hint doesn't work, could you try running schematic/manifest/examples/generator.py from command line?

This will particularly test manifest generation and verify that given the config.yml file 
- the schema is located correctly
- the manifest type in the manifest generation example is defined in the schema
- the google credentials work
- the google sheet API is successfully accessed

**Comment by BrunoGrandePhD** [comment]
Thanks for the tip, @allaway! That did the trick. I also confirmed that authentication was set up using the `generator.py` script that @milen-sage pointed to. 

When running `metadata_model.py`, I used my personal Sage Google account to authenticate. In general, would a Google account be created for each network for use with schematic?

**Comment by milen-sage** [comment]
I think we need to have clear documentation on how to create a google account for each network; and how to get the needed credentials for that account, so that each network would have their own credentials files. (Google credentials instructions are convoluted and I don't think it is sufficient for the documentation to ask the user to create a google account and retrieve the google service account and OAuth credentials: there are different kinds of services/scopes the OAuth credentials can be associated with; not everyone is aware of these details and that might cause confusion...)

Right now network administrators reuse the credentials files for the HTAN account we had created. That is fine if for the most part the network administrators are the same across the networks, but as more networks/projects are added it wouldn't scale.

**Comment by milen-sage** [comment]
Sounds like we are on our way of documenting and the manifest generation was resolved, so closing the issue.
