### ISSUE TITLE
Rename the `Requires` (with an 's') CSV schema column

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#283]
The motivation for renaming the `Requires` (with an `s`) column is to avoid confusion with the `Required` (with a `d`) column. Quick glances at the documentation can miss that one-letter difference. Alternative names include:

- `DependsOn`
- `Implies`
- `ImpliedAttributes`
- `RelevantAttributes`
- `AssociatedWith`

I think one important factor to consider when picking a new name is that the listed attributes **can** be set if the current entity come up, not that they **must** be set. This is another reason why `Requires` isn't great at conveying this message, and why I suggest changing it rather than `Required`.

**Comment by milen-sage** [comment]
Need to decide whether to 
- drop support for Requires once this is implemented and tested
- leave Requires in the code base, remove from examples, and mark it as obsolete in docs (so that people don't create new schemas using it)
- support Requires providing backward compatibility for existing schemas (so that people don't need to regenerate new schemas)

I lean towards either of the first two options since it's easy enough to regenerate a schema with the renamed field, so no backward compatibility is needed. Option 1 is easier wrt refactor and code maintenance; option 2 seems more user friendly :)

**Comment by BrunoGrandePhD** [comment]
Since it's a single-field fix that users only need to do once per schema floating around (which are limited in number), I vote for option 1 with a meaningful error message if `Requires` is ever detected in the CSV header. The error message can be something along the lines of:

> The input CSV schema file contains the `Requires` column header. To minimize confusion, this column was renamed to `DependsOn`. Please re-run with the new column name.

**Comment by BrunoGrandePhD** [comment]
This will be done in the `bgrande/rename-requires-column` branch.

**Comment by BrunoGrandePhD** [comment]
Solved by #345.
