### ISSUE TITLE
Review and refactor 'recursive dataset search' feature

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#318]
This feature was first implemented by @allaway [here](https://github.com/nf-osi/NF_data_curator/commit/ad7f1c81b8d54486d1963ce448c17e16a4add30c) in the Data Curator App. This issue tracks the implementation of this feature in the backend (_i.e._ schematic). Briefly, this feature extends the scope of datasets to any folder within a target Synapse project (rather than just the top-level folders).

**Comment by allaway** [comment]
Just for context, my implementation was a front end hack, but it works. I agree that this should be handled on the backend!

**Comment by ychae** [comment]
@BrunoGrandePhD @milen-sage is this being worked on for this phase?

**Comment by BrunoGrandePhD** [comment]
IMHO, I wouldn't prioritize this for this phase because there's already a front-end fix and you can specify any dataset folder you want at the command line. I don't see any urgency to implement this.

**Comment by allaway** [comment]
I am happy to PR that front-end fix to the shiny app if that would be
helpful (ie. if others need it).

**Comment by BrunoGrandePhD** [comment]
@allaway: Do you list all folders in a project? Or only folders that meet a certain criteria (_e.g._ that have a special annotation, like `contentType=dataset`)?

**Comment by allaway** [comment]
We list all folders in the project because we have no folder-level concept of 'dataset' (and it would probably be too challenging to retrofit to our projects). This is basically the change (though don't hold me to this, it's been a while since I made the change so could be forgetting things):

```
folder_list <- syn_store$getStorageDatasetsInProject(synStore_obj, project_synID)
folders_namedList <- c()
for (i in seq_along(folder_list)) {
    folders_namedList[folder_list[[i]][[2]]] <- folder_list[[i]][[1]]
}
folderNames <- names(folders_namedList)
```

replace with 

```
folder_df <- syn_tableQuery(sprintf("select name, id from %s where type = 'folder' and projectId = '%s'", config$main_fileview, project_synID))$asDataFrame()
                     
folders_namedList <- setNames(as.list(folder_df$id), folder_df$name)
folderNames <- names(folders_namedList)
```

could easily change this:
`syn_tableQuery(sprintf("select name, id from %s where type = 'folder' and projectId = '%s'", config$main_fileview, project_synID))$asDataFrame()`

to something like:

`syn_tableQuery(sprintf("select name, id from %s where contentType = 'dataset' and type = 'folder' and projectId = '%s'", config$main_fileview, project_synID))$asDataFrame()`

Could even rewrite all of this so it is configurable...something like:

if config$dataset_folders_only is TRUE
```
query <- glue::glue("select name, id from {config$main_fileview} where contentType = 'dataset' and type = 'folder' and projectId = {project_synID}")
```
else
```
query <- glue::glue("select name, id from {config$main_fileview} type = 'folder' and projectId = {project_synID}")
```

or even alternatively adding this to the shiny config: 

config$dataset_query_clauses = `contentType = 'dataset' and type = 'folder'`

```
query <- glue::glue("select name, id from {config$main_fileview} where {config$dataset_query_clauses} and projectId = {project_synID}")
```
