### ISSUE TITLE
Rewriting subpackage-specific README and example scripts

### ISSUE THREAD

**Issue by sujaypatil96** [Sage-Bionetworks/schematic#360]
**Is your feature request related to a problem? Please describe.**
Per our discussions, we want to change the content within the README's in each of the sub-packages in [`schematic`](https://github.com/Sage-Bionetworks/schematic/tree/develop/schematic)'s core folder.

**Describe the solution you'd like**
We decided that it would be best if the `examples` folder within each sub-package had a script (that can be run as a standalone module) consolidating the most important methods (not all) from the subpackage. The README following that would contain instructions on how to run the standalone script.

**How important is this feature?**
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?**
• Short-term - 2-4 weeks

**Comment by milen-sage** [comment]
@sujaypatil96 not related to the issue specifics (which are good), when opening new issues could you select 'New Issues' (under Pipelines in upper right corner in zenhub), otherwise by default the issues are placed in the first zenhub workspace lane, which happens to be long-term epics and makes them harder for PMs to see.

**Comment by sujaypatil96** [comment]
Thanks @milen-sage, will keep that in mind. I used to create issues through GitHub's interface (and not Zenhub), but I'll start using the Zenhub interface from now.

**Comment by sujaypatil96** [comment]
READMEs updated per changes in PR #392.
