### ISSUE TITLE
Reducing Google sheet API write requests further

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#453]
@sujaypatil96 do you think we can try evaluate what's causing this:

Warning: Error in py_call_impl: HttpError: <HttpError 429 when requesting https://sheets.googleapis.com/v4/spreadsheets/1w1NaYtei7892VV9DRpsj444fELGjLX1Dpt2GT9qr7Bc/values/Sheet1%21A1%3ACJ1?valueInputOption=RAW&alt=json returned "Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:269908437164'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'consumer': 'projects/269908437164', 'quota_metric': 'sheets.googleapis.com/write_requests', 'quota_limit': 'WriteRequestsPerMinutePerUser', 'service': 'sheets.googleapis.com'}}]">

Despite the recent batch request changes we get that error quite frequently.  I don't think it's due to the number of concurrent users requesting google sheets (nor invisible columns and associated requests in manifests).

E.g. substantial fraction of requests to generate the diagnosis template for the manifest here
https://www.synapse.org/#!Synapse:syn25010285

result in the error above. Granted, this is the manifest containing perhaps the largest number of columns.

Perhaps you can benchmark the number of requests generated to Google's API for it?

Perhaps also check out lines [412](https://github.com/Sage-Bionetworks/schematic/blob/bafeb8ceb3019351b8aa2f971394bc2b1eda0dea/schematic/manifest/generator.py#L412
) and [416](https://github.com/Sage-Bionetworks/schematic/blob/bafeb8ceb3019351b8aa2f971394bc2b1eda0dea/schematic/manifest/generator.py#L416) in manifest generator. They could be combined in a single batch request? Though, benchmarking number of Google API's requests would still be a good idea.

**Comment by sujaypatil96** [comment]
An immediate fix to unblock data contributors from accessing and submitting manifests with large number of columns (e.g., `Diagnosis` data type) was to request Google Cloud Support to increase our API quota for the limit **Write requests per minute per user** from 60 to 300.

You can check the limit by logging into the [`Google Developers Console`](console.cloud.google.com) > IAM and Admin > Quotas > Write requests per minute per user (ALL QUOTAS).

This is still no reason for us not to improve our requests by batching where we can [generator.pyL#282](https://github.com/Sage-Bionetworks/schematic/blob/bafeb8ceb3019351b8aa2f971394bc2b1eda0dea/schematic/manifest/generator.py#L282), but I think we can close this issue for now since it solves the problem. Your thoughts @milen-sage?

**Comment by milen-sage** [comment]
Yes, we can close this for now; the manifest generation google API calls optimization can wait until we decide to refactor manifest generator to decouple google API calls from a more general manifest generation interface.
