### ISSUE TITLE
Add additional functionality to populateModelManifest so that it can "detect" new datasets that get uploaded

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#627]
**Is your feature request related to a problem? Please describe.**
This issue is related to Milen's comment mentioned in this [PR](https://github.com/Sage-Bionetworks/schematic/issues/607). Currently, the populateModelManifest function only turns a local manifest file to a Google sheet. But in the future, we want it to be able to detect new files that got added to the dataset. For example, if a manifest generated by using "BulkRNA-seqAssay" as a data component only contains "Sample_A" (under column "filename"), we would want the function to be able to detect "Sample_B" that later got added to the folder.  

Example dataset folder can be found [here](https://www.synapse.org/#!Synapse:syn28268700)

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**
Acceptance criteria:  the populated manifest google sheet contains newly added files to dataset

**Comment by ychae** [comment]
@milen-sage will look into schematic's function on how we populate manifests on existing dataset files (manifest generator code)

**Comment by milen-sage** [comment]
In schematic, we don't currently pull the latest set of dataset files into the populated manifest by default. I'll create a separate issue.

@rrchai how does the DCA currently pull the latest list of files, when a manifest is generated?

**Comment by rrchai** [comment]
@milen-sage Correct me if I am wrong, `getModelManifest` is able to get list of files in the dataset. It is used in the current DCA. I believe this pr #523 is addressing this issue?

**Comment by milen-sage** [comment]
@rrchai - ah perfect! I thought I added this functionality, but then started doubting my memory :) since I didn't see it when I was browsing through the manifest generation code today. I see now the relevant logic is in store/synapse.py

@linglp could you take a look at this [route](https://github.com/Sage-Bionetworks/schematic/blob/8efa7296a6f3381b12e3640e63d3f6b8f1b6a8c7/api/routes.py#L70)? Doesn't it do what we want the [populate manifest route](https://github.com/Sage-Bionetworks/schematic/blob/8efa7296a6f3381b12e3640e63d3f6b8f1b6a8c7/api/routes.py#L166) to do?

A side note in case it's useful [this function](https://github.com/Sage-Bionetworks/schematic/blob/8efa7296a6f3381b12e3640e63d3f6b8f1b6a8c7/schematic/store/synapse.py#L325) is used to update the dataset files by get_manifest in the get_manifest_route call.

**Comment by linglp** [comment]
@milen-sage  Thank you! I just tested it out by using the GET /manifest/generate endpoint and when I tried to get an existing manifest, I could see new entity IDs get added for new datasets. If that works, do we still want to expose an additional endpoint for the updateDatasetManifestFiles function?

**Comment by milen-sage** [comment]
@afwillia could you confirm you can use the existing endpoint @linglp mentioned? 

@linglp that's valuable feedback, we did mention [here](https://github.com/Sage-Bionetworks/schematic/issues/607#issue-1169787090) that it's possible an endpoint already exists.

**Comment by afwillia** [comment]
@milen-sage @linglp the original manifest/generate command works

**Comment by linglp** [comment]
This ticket can be closed because we could use an existing endpoint.
