### ISSUE TITLE
VR's: Append trailing comma to a string when expecting a list

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/schematic#653]
**Is your feature request related to a problem? Please describe.**
Related to PR #650. Was brought up in one of the last comments that it would be nice for single value lists to be able to automatically either add a comma or ignore that there is not a comma so as to not throw a validation error that the list is not formatted properly.

This might need discussion prior to any implementation, bc the error exists to catch lists that are uploaded without commas. It might be better to just force people to add trailing commas than to add commas and potentially let bad lists through.
**Describe the solution you'd like**

Allow single value lists to pass validation without an error. 
**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by allaway** [comment]
As an app _user_ my preference would be:  ignore that there is not a comma for single value lists :) 

"It might be better to just force people to add trailing commas than to add commas and potentially let bad lists through."

At least in our schema, most or all of our list-columns have a set list of valid values. Therefore, if someone has a "bad list," it will not pass validation because it will not match the list of valid values. 

IMO, people will be very confused by needing to add a trailing comma to single-value lists.

**Comment by allaway** [comment]
In thinking about this a little more, what we really need is to tell schematic able to ignore list _validation_, but to still tell schematic to parse the input as a list and then validate each member of that list (even a list of one) against a set of valid values. 

For NF, I'm creating a patch here https://github.com/Sage-Bionetworks/schematic/commit/a9f269783841ed83759cdf49d5c54a73d32cb17f to unblock our DCA until we can figure out how best to implement this in schematic.
