### ISSUE TITLE
Valid Values Mixed Up

### ISSUE THREAD

**Issue by brynnz22** [Sage-Bionetworks/schematic#672]
For CSBC, when I generate manifests for the `Theme` and `Consortium` components, the valid values are mixed up between the name attributes. For example Consortium Name, Consortium Display Name, and Consortium Full Name are not showing the correct valid values - sage_bionetworks is a correct value for Consortium Name, but not for Consortium Display Name (it should be Sage Bionetworks). Attached are the data model csv, the google doc for the data model, and the example manifests for Theme and Consortium. I could not attach the jsonld and config.yml files. 

**To Reproduce**
1. Edit config.yml file to generate Consortium or Theme for the data_type
2. Generate manifest for Consortium and Theme using the command: schematic manifest --config /Users/bzalmanek/Documents/csbc_schematic/schematic/config.yml get -s -oauth
3. Examine valid values for Consortium Name, Consortium Display Name, and Consortium Full Name

**Expected behavior**
The valid values for the above attributes will match the valid values in the data model. 

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [ x] Critical 🆘

**Desktop (if applicable, please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]

CSBC data model: https://docs.google.com/spreadsheets/d/1hbG1vdi8a0gc-6psn5VgsBgyMl6IOhDSbHWDuC_8EXo/edit#gid=59750547

[csbc.model.csv](https://github.com/Sage-Bionetworks/schematic/files/8498826/csbc.model.csv)

Example of Consortium Manifest: https://docs.google.com/spreadsheets/d/1AN-Hd2pilaH4J1fuvutyjd-Bm1jqvIrFEpk26UucTG8/edit#gid=0

Example of Theme Manifest: https://docs.google.com/spreadsheets/d/1E-QtYEnyq26F7UrkpOLJ-O61LI_Y7-PeWl4IK-YvPjU/edit#gid=0

**Comment by mialy-defelice** [comment]
I assigned myself bc I'm starting to look into this bug, but feel free to re-assign.

**Comment by mialy-defelice** [comment]
Closing this issue since @brynnz22 said it was not currently an issue any longer.

Some notes on why this behavior was being seen:

This is essentially coming down to how in the JSON LD the valid values are all being recorded as 'SageBionetworks' through the function `se.get_class_label_from_display_name(val)`:

```
(Pdb) se.get_class_label_from_display_name('sage_bionetworks')
'SageBionetworks'
(Pdb) se.get_class_label_from_display_name('Sage Bionetworks')
'SageBionetworks'
(Pdb) se.get_class_label_from_display_name('CSBC')
'CSBC'
(Pdb) se.get_class_label_from_display_name('csbc')
'Csbc'
(Pdb) se.get_class_label_from_display_name('icbp')
'Icbp'
(Pdb) se.get_class_label_from_display_name('NCI')
'NCI'
(Pdb) se.get_class_label_from_display_name('Nci')
'Nci'
(Pdb) se.get_class_label_from_display_name('PS_ON')
'PSON'
(Pdb) se.get_class_label_from_display_name('PS-ON')
'PS-ON'
(Pdb) se.get_class_label_from_display_name('sage__bionetworks')
'Sage_bionetworks'
```

When the JSONLD is then getting converted to the manifest, `SageBionetworks` is then being converted back to `sage_bionetworks` since the display name for `SageBionetworks` is now being saved as `sage_bionetworks` as can be seen in the JSONLD:

```
{
            "@id": "bts:SageBionetworks",
            "@type": "rdfs:Class",
            "rdfs:comment": "TBD",
            "rdfs:label": "SageBionetworks",
            "rdfs:subClassOf": [
                {
                    "@id": "bts:ConsortiumName"
                }
            ],
            "schema:isPartOf": {
                "@id": "http://schema.biothings.io"
            },
            "sms:displayName": "sage_bionetworks",
            "sms:required": "sms:false",
            "sms:validationRules": []
        },

```

Testing how naming changes could overcome this issue:

So by replacing `sage_bionetworks` in the Data Model with `sage-bionetworks` I was able to approximate the naming. It gives differing Display Names making `Consortium Display Names` valid values include `Sage Bionetworks` and `Consortium Name`  valid values include `sage-bionetworks`.
