### ISSUE TITLE
Incorporating Attributes not specified in DependsOn column into Manifest

### ISSUE THREAD

**Issue by brynnz22** [Sage-Bionetworks/schematic#692]
**Describe the bug**
For the CSBC data model - when generating a `Tool` manifest or a `Tool View` manifest, the attribute `Name` is being added at the end of the manifests, though this attribute is not specified in the `DependsOn` column for the `Tool` or `Tool View` components. It is specified as part of the `Person` component. 

**To Reproduce**
1. Download current csv of the data model from this [google doc](https://docs.google.com/spreadsheets/d/1hbG1vdi8a0gc-6psn5VgsBgyMl6IOhDSbHWDuC_8EXo/edit#gid=59750547)
2. Convert to jsonLd using schematic - this command: `schematic schema convert -v INFO /path/to/csv/file`
3. Generate `Tool` or `Tool View` manifest using this command: `schematic manifest --config /path/to/config.yml get -s -oauth`
4. See manifest(s)

**Expected behavior**
The manifest(s) will generate and the attribute `Name` will not be in the manifest. Only the attributes specified in the `DependsOn` column.

**Priority** (select one)
- [ ] Minor ⬇️
- [ X] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**
 - OS: [Mac]
 - Browser [Chrome]
 - Version [?]

**Comment by milen-sage** [comment]
@brynnz22 for reproduction, could you add the manifest(s) you generated (for Tool and/or Tool View) to this issue? Thanks!

**Comment by brynnz22** [comment]
Yes. Here is the [toolView.manifest](https://docs.google.com/spreadsheets/d/1PKKPEqi3nJ7NxKy0ZAd_iSABfCNK11jftBYPVe4Mu5o/edit#gid=0) and here is the [tool.manifest](https://docs.google.com/spreadsheets/d/124PCfqctV6Tt6jvRzrAjqTrzpn5T6t8FBkCBFMbqjsQ/edit#gid=0)

**Comment by mialy-defelice** [comment]
@ychae Tagging to keep you in the loop.

@brynnz22 Hey Brynn! Sorry it took us so long to get this ticket addressed!!

I had a look through your data model and was able to find the source of what was causing `Name` to appear in the `Tool` and `ToolView` manifests. When picking valid values, one unfortunately cannot repeat an attribute name as a valid value (@ychae this might be a good ticket to reference in the issue about aliasing attribute names) or else that attribute will now be linked to your current attribute. 

In this case both `Tool Input Data` and `Tool Output Data` both contained `Name` as a valid value. Since `Tool` depends on both `Tool Input Data` and `Tool Output Data` the attribute `Name` was inadvertently associated with `Tool` . Removing `Name` as a valid value resolved the issues with the manifests containing `Name` in the final column. I linked the updated manifests below.

I am attaching the CSV with `Name` removed bc it's so hard to find, so you can just copy those cells back into your model to save time. Unfortunately, the only way to add `Name` back as a valid value in any real sense is to give it a uniquely identifying name or to change the name of the `Name` attribute. Sorry if that's confusing...'name' was repeated a lot.

Let me know if you have any questions!!

[csbc_data_model_modified.csv](https://github.com/Sage-Bionetworks/schematic/files/8894799/csbc_data_model_modified.csv)

[Tool Manifest
](https://docs.google.com/spreadsheets/d/1QoEAEg2FqHqfLTd557NjYNMG_-ujbE5r2x3U5czNB4I/edit#gid=0)

[Tool View Manifest](https://docs.google.com/spreadsheets/d/1dTvd4xRB3Gz4btOtO68olmNMCfUJuDGHOMuKrcZvPIA/edit#gid=0)

**Comment by brynnz22** [comment]
@Sage-Bionetworks/challenge-registry-admins Thank you so much! This makes sense. We have not used "Name" as an annotation so far for Tools, so it worked out removing it as a valid value for inputData and outputData.
