### ISSUE TITLE
Check if we are using OOB OAuth with Google services

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#898]
https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

**Comment by linglp** [comment]
@milen-sage I think this issue is related to an old issue that I have done before. See #705 

In addition to the comment that I have written for the old issue, I also find out that in our `generate_token` method [here](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/utils/google_api_utils.py#:~:text=def%20generate_token()), there's a part that goes like this: 
```
        else:
            flow = InstalledAppFlow.from_client_secrets_file(CONFIG.CREDS_PATH, SCOPES)
            creds = flow.run_console()  ### don't have to deal with ports

```

and `run_console` method is going to get deprecated based on the documentation [here](https://googleapis.dev/python/google-auth-oauthlib/latest/_modules/google_auth_oauthlib/flow.html#:~:text=%5Bdocs%5D-,def%20run_console(,-self%2C%0A%20%20%20%20%20%20%20%20authorization_prompt_message ) Since we don't define `_OOB_REDIRECT_URI` in our code, by default class `InstalledAppFlow` is using `_OOB_REDIRECT_URI = "urn:ietf:wg:oauth:2.0:oob"` (see documentation [here](https://googleapis.dev/python/google-auth-oauthlib/latest/_modules/google_auth_oauthlib/flow.html#:~:text=class%20InstalledAppFlow(Flow)%3A))

**Comment by milen-sage** [comment]
This is good to know and it's the extent of what we'd like to know now.  Thanks @linglp! 

It sounds like we'd want to prioritize outlining the work to transition away from the deprecated features. I'll create a milestone and add a couple of issues related to what you discovered. I might reach out to see if I understood correctly.
