### ISSUE TITLE
JIRA Migration - Support Censored and Uncensored Tables

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#920]
Delineate related issues and migrate them to Jira. (03/05/23)

**Is your feature request related to a problem? Please describe.**
Separate manifest uploads to censored and uncensored tables

**Describe the solution you'd like**
Split censored and uncensored manifest table uploads accordingly.

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by MiekoHash** [comment]
Hi @GiaJordan and @milen-sage, I plan to move this to JIRA before sprint '5' which starts on March 6. Since the ticket needs to be divided into smaller issues, and then go through refinement and triage process, I think we would like to target actual work to start in sprint '6' if definition of ready is satisfied. Does it sound like a reasonable timeline? I'm also taking homeweek and following week's no-meeting days into consideration.

**Comment by GiaJordan** [comment]
@MiekoHash That sounds fine! Could a ticket be added to my sprint 5 to allot time for breaking down the ticket into smaller issues?

**Comment by MiekoHash** [comment]
Hi @GiaJordan This ticket has been moved to https://sagebionetworks.jira.com/browse/FDS-44. In order to create an Epic ticket in JIRA, "Epic Name" is needed. I put some text in there but please feel free to change. 
I know there are several more feature tickets under ["Table Behavior" milestone](https://github.com/Sage-Bionetworks/schematic/milestone/31) so I will let you move them to JIRA at your own pace. Next weekly refinement meeting is on the 10th. If any broken down tickets are ready by then, we can start processing them through the refinement/triage process. Thanks.  cc @milen-sage
