### ISSUE TITLE
Document how to generate an excel spreadsheet vs google sheet in schematic

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#938]
Related to #932 - document how to use this option for template generation.

AC:
- in-code documentation, compatible with #894, for relevant methods
- if adding to CLI as option, document in CLI; similarly to swagger documentation if adding to REST API

**Comment by linglp** [comment]
@milen-sage I think in CLI, we already have `--xlsx` flag. Since we are only changing how the Excel spreadsheet gets generated, the function should be used in the same way as `--xlsx`. Let me know if there's anything that needs to be changed for `--xlsx` flag documentation. 

Swagger UI is update to date. I think we will try to use pdoc for schematic functions instead of using it for the APIs, so I skip this part.
