### ISSUE TITLE
schematic: spot check entity migration manifest updates

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#959]
Following up on https://github.com/Sage-Bionetworks/schematic/issues/861. 

As reported by @clarisse-lau, after migrating entities some manifests contain fewer entities than they should based on the previous manifest version. 

For example, in the version history of a biospecimen manifest: [v1](https://www.synapse.org/#!Synapse:syn35488819.1) contains much more data : 772 records; v3 after entity migration contains only 40. They are likely more examples.

AC: 
- diagnose the issue and reproduce the behavior
- restore HTAN data
- redo migration to avoid data loss

**Comment by milen-sage** [comment]
@adamjtaylor this is highest priority.

**Comment by adamjtaylor** [comment]
FYI @clarisse-lau @aclayton555

**Comment by GiaJordan** [comment]
The issue above was due to the switch in manifest naming convention. Some manifests were uploaded by users after the switch occurred, and schematic is not currently equipped with logic to choose between multiple manifests except in the case where there are censored and uncensored versions are present. During the migration, schematic pulled the latest `synapse_storage_manifest.csv` and uploaded manifests as `synapse_storage_manifest_{component}.csv`. In the case where the error occurred, the latest version of the manifest, which had the component appended to the name, was not pulled and an older version was used.

**Each version is still present on synapse**, and additional logic will be added to schematic for the HTAN entity migration to pull the latest version of each manifest not modified by myself, after which the entity migration and table uploads will be re-performed.

@adamjtaylor @clarisse-lau @aclayton555

**Comment by GiaJordan** [comment]
Currently reviewing previously migrated projects to gauge scope of duplicate manifest issue, and re-migrating as appropriate. Will proceed with initial migration of remaining projects afterwards
@adamjtaylor @clarisse-lau @aclayton555 @elv-sb 
cc @milen-sage

**Comment by GiaJordan** [comment]
After running the manifest selection code to determine the scope of the problem, it looks like the only projects that have had manifests uploaded with entityIDs before I performed their migration are as follows:
Relevant:
- Vanderbilt
- OHSU
- HMS

Not Applicable:

- BU
- WUSTL
- CHOP
- MSK
- DFC
- Duke
- Stanford

I'll now proceed with the migration of the remaining projects

**Comment by clarisse-lau** [comment]
Thank you @GiaJordan!

**Comment by GiaJordan** [comment]
@clarisse-lau you're welcome!
