### ISSUE TITLE
manifest/generate endpoint returns xlsx in response instead of filepath

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/schematic#978]
**Is your feature request related to a problem? Please describe.**
The manifest/generate API endpoint can now return an xlsx file, yay! But it downloads the file to the server and returns a file path. This will be problematic for the future serverless DCA + schematic architecture because we want to avoid reading and writing files. 

Also, it will likely throw an error in a container similar to [this issue for storage/assets/table](https://github.com/Sage-Bionetworks/schematic/issues/863) since the output file path is fixed.

Edit: [This is the endpoint](https://github.com/Sage-Bionetworks/schematic/blob/166c6ead789cd9d24858a6f3f453f18478555132/api/routes.py#L355)

**Describe the solution you'd like**
Return the xlsx file in the API response.

**Comment by linglp** [comment]
@milen-sage and @afwillia currently, `/manifest/generate` endpoint could also return multiple manifests (with different data types). But I don't think API could return multiple files (unless it is a zip file). Should I try figuring out returning a zip file if users want to return multiple manifests in Excel format? Or should I just return one return Excel file and add documentation/warning to remind users?

**Comment by afwillia** [comment]
@milen-sage  @linglp The core DCA functionality only accesses one manifest at a time. However, the dashboard downloads all of the manifests in a loop and merges it to the synapse metadata. It could be possible in the future to refactor using the multiple manifest download option, especially it merges the synapse metadata. But as of right now, I don't know much about the use cases for getting multiple manifests at once.

**Comment by milen-sage** [comment]
@linglp let's not worry about returning multiple excel spreadsheets at once for this sprint. Agreed it is indeed a bit inconsistent since we allow that for other formats. Perhaps something to consider in a future sprint - could you add a GH issue? I like the zip option and there are programmatic python tools to do that.

Also agreed with @afwillia we don't have immediate use cases, but can see it becoming relevant in the future (e.g. munging manifests together; or allowing generating multiple spreadsheets at once through the app and returning these as a zip).

**Comment by linglp** [comment]
Okay sounds good. Thank you both! I have captured the issue related to returning multiple manifests as a zip in #992
